# NovaBungeeAnnouncer config file
 
# Order, either sequential or random
order: random
# The server that should be asked for permissions (Most likely the hub server)
permissionServer: hub
# How often the permissions cache is cleared in minutes. (0=never)
permissionCacheTime: 0
# A list of announcements (See spigot page for usage)
servers:
  hub: !!AnnouncerConfig$MessageMap
    announcements:
    - message: '[{"text":"/ ","color":"blue","bold":true},{"text":"// ","color":"aqua","bold":true},{"text":">> ","color":"dark_gray","bold":false},{"text":"is run by, ","color":"yellow"},{"text":"[placeholder]","color":"aqua"}]'
      type: json
   delay: 1200
   offset: 0
   permission: null
   servers: null
nonannouncements:
  demo: !!AnnouncerConfig$BroadcastMap
    announcement:
      message: Hello, <user>
      type: text
    permission: super.op
    servers:
   - global